[package]
name = "showsomethings"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = { version = "*" }
vulkano = { version = "*" }
vulkano-shaders = { version = "*" }
# image = { version = "*" }
log = "*"
env_logger = "*"
glam = "*"
